### ISSUE TITLE
warnings with PHP7.1.0

### ISSUE THREAD

**Issue by matkatmusic** [0xbb/php-sha3#2]
in the keccak64() function, on line 123, I'm getting warnings of "A non-numeric value encountered". 
I understand that $temp is padded with 0's on line 120.  

I'm testing it with randomly generated strings and the hashed results match https://emn178.github.io/online-tools/sha3_512.html's results.    So, it's definitely not broken functionality or anything.   I'm just curious if it is something that needs fixing.

**Comment by matkatmusic** [comment]
you can see the warnings here when you press execute: http://sandbox.onlinephpfunctions.com/code/2cff38a76f78065f77fb435fa46a9d27c52b6b64

**Comment by matkatmusic** [comment]
calling: echo SHA3::hash("abcde", 512);

<br />
<b>Warning</b>:  A non-numeric value encountered in <b>[...][...]</b> on line <b>123</b><br />
<br />
<b>Warning</b>:  A non-numeric value encountered in <b>[...][...]</b> on line <b>123</b><br />
1d7c3aa6ee17da5f4aeb78be968aa38476dbee54842e1ae2856f4c9a5cd04d45dc75c2902182b07c130ed582d476995b502b8777ccf69f60574471600386639b

**Comment by matkatmusic** [comment]
Ok, the folks over in ##php said this is the fix: 

123: $temp[$rsiz - 1] = chr(ord($temp[$rsiz - 1]) | 0x80);

**Comment by BasMatthee** [comment]
I just noticed the exact same thing today using PHP 7.1. Please apply the fix.
